In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
import tweepy
import spacy
import en_core_web_sm
import pickle

In [2]:
TWITTER_API_KEY = "RhLwEal1HaKFO96oXiYjHDlC6"
TWITTER_API_KEY_SECRET = "4BLMVQbNnJ3PDB4518MW2Z772b7TBBPlUeXcS8KBdYFqKIg2c9"

In [3]:
auth = tweepy.OAuthHandler(TWITTER_API_KEY, TWITTER_API_KEY_SECRET)

In [4]:
twitter = tweepy.API(auth)

In [5]:
twitter

In [6]:
nasa = twitter.get_user("nasa")

In [7]:
nasa

User(_api=<tweepy.api.API object at 0x000001ED58719940>, _json={'id': 11348282, 'id_str': '11348282', 'name': 'NASA', 'screen_name': 'NASA', 'location': 'Pale Blue Dot', 'profile_location': None, 'description': "There's space for everybody. ✨", 'url': 'https://t.co/HMJJbimQpV', 'entities': {'url': {'urls': [{'url': 'https://t.co/HMJJbimQpV', 'expanded_url': 'http://www.nasa.gov/', 'display_url': 'nasa.gov', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 48046034, 'friends_count': 175, 'listed_count': 96343, 'created_at': 'Wed Dec 19 20:20:32 +0000 2007', 'favourites_count': 13114, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': True, 'statuses_count': 66285, 'lang': None, 'status': {'created_at': 'Wed Aug 18 23:12:00 +0000 2021', 'id': 1428132601299050499, 'id_str': '1428132601299050499', 'text': "🔭 What's up in the night sky? The Perseid meteor shower has peaked — but there's a great opportunity to spot Jupite… http

In [8]:
# Getting user id
nasa.id_str

'11348282'

In [9]:
jeff = twitter.get_user("jeffbezos")

In [10]:
jeff

User(_api=<tweepy.api.API object at 0x000001ED58719940>, _json={'id': 15506669, 'id_str': '15506669', 'name': 'Jeff Bezos', 'screen_name': 'JeffBezos', 'location': '', 'profile_location': None, 'description': 'Amazon, Blue Origin, Washington Post', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 2593712, 'friends_count': 1, 'listed_count': 8850, 'created_at': 'Sun Jul 20 22:38:36 +0000 2008', 'favourites_count': 1, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': True, 'statuses_count': 241, 'lang': None, 'status': {'created_at': 'Fri Feb 28 17:17:58 +0000 2020', 'id': 1233441223232245760, 'id_str': '1233441223232245760', 'text': 'Discussing climate, sustainability, and preserving the natural world with President @EmmanuelMacron today in Paris.… https://t.co/ry52OGekMH', 'truncated': True, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'EmmanuelMacron', 'name': 'Emmanuel Macron', 'id':

In [11]:
jeff.created_at

datetime.datetime(2008, 7, 20, 22, 38, 36)

In [12]:
jeff.location

''

In [13]:
jeff.description

'Amazon, Blue Origin, Washington Post'

In [14]:
for friend in jeff.friends():
    print(friend.screen_name)

mackenziescott


In [15]:
for friend in nasa.friends():
    print(friend.screen_name)

NASA_Gateway
Astro_Pam
SenBillNelson
Aki_Hoshide
Thom_astro
NASAArtemis
dominickmatthew
uaespaceagency
Astro_Megan
KathyLueders
MarkKirasich
Astro_SEAL
NASARoman
NASAPersevere
DoNASAScience
NASA_Marshall
JonnyKimUSA
AEM_mx
isro
ILSpaceAgency


In [16]:
nasa_tweets = nasa.timeline(count=200, exclude_replies=True, include_rts=False, tweet_mode="Extended")

In [17]:
jeff_tweets = jeff.timeline(count=200, exclude_replies=True, include_rts=False, tweet_mode="Extended")

In [18]:
jeff_tweets[0].id

1233441223232245760

In [19]:
jeff_tweets[0].text

'Discussing climate, sustainability, and preserving the natural world with President @EmmanuelMacron today in Paris.… https://t.co/ry52OGekMH'

In [20]:
nasa_tweets[0].text

"🔭 What's up in the night sky? The Perseid meteor shower has peaked — but there's a great opportunity to spot Jupite… https://t.co/a6NvGrnfvs"

In [21]:
nlp_model = en_core_web_sm.load()

In [22]:
nlp_model

In [23]:
word2vec = nlp_model('Hello World').vector

In [24]:
word2vec

array([ 0.02253607, -0.5658325 ,  0.2835284 , -0.5005794 , -0.44492146,
       -0.3338291 , -0.6768952 , -0.5755814 , -0.3506569 , -0.5828593 ,
        0.33561912, -0.7989587 , -0.32728213,  0.28652003, -0.09790938,
       -0.34096682,  0.93680906, -0.04700723, -0.1254418 ,  0.05007662,
        0.6271533 , -0.26864648, -0.26104075,  0.3102935 , -0.18258318,
        0.37482244, -0.1958755 , -0.269704  ,  0.18854724,  0.42074004,
        0.37014163, -0.21506017, -0.23147771, -0.07678793, -0.08126494,
       -0.01016814, -0.33158696,  0.8419969 ,  1.4209404 ,  0.5966831 ,
       -0.01925323, -0.41349357,  0.04606276,  1.3453022 ,  0.49630496,
       -0.64539725,  0.44891363,  0.0381873 , -0.5331311 ,  0.03031451,
        0.30793014, -0.15499681,  0.26014906, -1.0830808 , -0.16309868,
       -0.8180718 ,  0.05043671,  0.48304605, -0.7510787 , -0.31343704,
        0.53932416, -0.05776475,  0.25793022, -0.14905885, -0.17369384,
       -0.30335104, -0.7591399 , -0.98595625,  0.55281687,  0.19

In [25]:
word2vec_nasa_last_tweet = nlp_model(nasa_tweets[0].text).vector

In [26]:
word2vec_nasa_last_tweet

array([ 1.85173616e-01, -1.33187264e-01,  6.39892966e-02,  5.79700731e-02,
        2.58966327e-01, -8.83494020e-02, -1.92539275e-01,  4.42613363e-02,
       -3.41210440e-02, -1.37922928e-01,  1.69979006e-01, -1.59201786e-01,
        1.83297262e-01, -1.45774379e-01, -4.45709415e-02, -1.05901539e-01,
        8.27725306e-02, -4.48699780e-02, -4.00798544e-02,  3.22756767e-02,
       -7.64865568e-03,  9.78409350e-02, -1.34760022e-01, -1.63172781e-01,
        9.38174725e-02, -2.77234297e-02, -1.06998317e-01,  1.03367336e-01,
        1.43353119e-01,  1.17691889e-01, -2.07241163e-01,  9.14771226e-05,
       -2.24608421e-01, -7.31307501e-03,  1.98062770e-02,  9.66169536e-02,
       -7.90692419e-02, -2.05112938e-02,  3.30743045e-02,  7.91417584e-02,
       -1.16363995e-01,  1.50330141e-01, -6.85996637e-02, -1.03802033e-01,
       -2.16518473e-02, -1.30617619e-01,  2.31081918e-02, -9.95141938e-02,
       -5.26558496e-02,  4.83925976e-02,  2.88570046e-01,  8.09854642e-02,
        6.94535449e-02,  

In [27]:
nlp_model.to_disk('my_nlp_model')

In [28]:
nlp_model2 = spacy.load('my_nlp_model')

In [29]:
word2vec_2 = nlp_model('Hello World').vector

In [30]:
word2vec_2

array([ 0.02253607, -0.5658325 ,  0.2835284 , -0.5005794 , -0.44492146,
       -0.3338291 , -0.6768952 , -0.5755814 , -0.3506569 , -0.5828593 ,
        0.33561912, -0.7989587 , -0.32728213,  0.28652003, -0.09790938,
       -0.34096682,  0.93680906, -0.04700723, -0.1254418 ,  0.05007662,
        0.6271533 , -0.26864648, -0.26104075,  0.3102935 , -0.18258318,
        0.37482244, -0.1958755 , -0.269704  ,  0.18854724,  0.42074004,
        0.37014163, -0.21506017, -0.23147771, -0.07678793, -0.08126494,
       -0.01016814, -0.33158696,  0.8419969 ,  1.4209404 ,  0.5966831 ,
       -0.01925323, -0.41349357,  0.04606276,  1.3453022 ,  0.49630496,
       -0.64539725,  0.44891363,  0.0381873 , -0.5331311 ,  0.03031451,
        0.30793014, -0.15499681,  0.26014906, -1.0830808 , -0.16309868,
       -0.8180718 ,  0.05043671,  0.48304605, -0.7510787 , -0.31343704,
        0.53932416, -0.05776475,  0.25793022, -0.14905885, -0.17369384,
       -0.30335104, -0.7591399 , -0.98595625,  0.55281687,  0.19

In [31]:
len(nasa_tweets)

114

In [32]:
len(jeff_tweets)

186

In [33]:
type(word2vec_nasa_last_tweet)

numpy.ndarray

In [34]:
nlp = spacy.load('C:/Users/me/OneDrive/Desktop/Desktop/Education/Lambda/Unit3-Sprint3/Twitoff/my_nlp_model')

In [35]:
def vectorize_tweet(tweet_text):
    return nlp(tweet_text).vector

In [36]:
nt = vectorize_tweet(nasa_tweets[0].text)

In [37]:
nt

array([ 1.85173616e-01, -1.33187264e-01,  6.39892966e-02,  5.79700731e-02,
        2.58966327e-01, -8.83494020e-02, -1.92539275e-01,  4.42613363e-02,
       -3.41210440e-02, -1.37922928e-01,  1.69979006e-01, -1.59201786e-01,
        1.83297262e-01, -1.45774379e-01, -4.45709415e-02, -1.05901539e-01,
        8.27725306e-02, -4.48699780e-02, -4.00798544e-02,  3.22756767e-02,
       -7.64865568e-03,  9.78409350e-02, -1.34760022e-01, -1.63172781e-01,
        9.38174725e-02, -2.77234297e-02, -1.06998317e-01,  1.03367336e-01,
        1.43353119e-01,  1.17691889e-01, -2.07241163e-01,  9.14771226e-05,
       -2.24608421e-01, -7.31307501e-03,  1.98062770e-02,  9.66169536e-02,
       -7.90692419e-02, -2.05112938e-02,  3.30743045e-02,  7.91417584e-02,
       -1.16363995e-01,  1.50330141e-01, -6.85996637e-02, -1.03802033e-01,
       -2.16518473e-02, -1.30617619e-01,  2.31081918e-02, -9.95141938e-02,
       -5.26558496e-02,  4.83925976e-02,  2.88570046e-01,  8.09854642e-02,
        6.94535449e-02,  

In [38]:
for tweet in nasa_tweets:
    print(tweet.text)
    print(vectorize_tweet(tweet.text))

🔭 What's up in the night sky? The Perseid meteor shower has peaked — but there's a great opportunity to spot Jupite… https://t.co/a6NvGrnfvs
[ 1.85173616e-01 -1.33187264e-01  6.39892966e-02  5.79700731e-02
  2.58966327e-01 -8.83494020e-02 -1.92539275e-01  4.42613363e-02
 -3.41210440e-02 -1.37922928e-01  1.69979006e-01 -1.59201786e-01
  1.83297262e-01 -1.45774379e-01 -4.45709415e-02 -1.05901539e-01
  8.27725306e-02 -4.48699780e-02 -4.00798544e-02  3.22756767e-02
 -7.64865568e-03  9.78409350e-02 -1.34760022e-01 -1.63172781e-01
  9.38174725e-02 -2.77234297e-02 -1.06998317e-01  1.03367336e-01
  1.43353119e-01  1.17691889e-01 -2.07241163e-01  9.14771226e-05
 -2.24608421e-01 -7.31307501e-03  1.98062770e-02  9.66169536e-02
 -7.90692419e-02 -2.05112938e-02  3.30743045e-02  7.91417584e-02
 -1.16363995e-01  1.50330141e-01 -6.85996637e-02 -1.03802033e-01
 -2.16518473e-02 -1.30617619e-01  2.31081918e-02 -9.95141938e-02
 -5.26558496e-02  4.83925976e-02  2.88570046e-01  8.09854642e-02
  6.94535449e-

In [39]:
nasa_tweets_vec = np.array([vectorize_tweet(tweet.text) for tweet in nasa_tweets])

In [40]:
nasa_tweets_vec

array([[ 0.18517362, -0.13318726,  0.0639893 , ...,  0.13086696,
         0.10103434, -0.09374696],
       [ 0.3437568 ,  0.30119976, -0.15932325, ...,  0.14604531,
         0.17708758,  0.01555557],
       [ 0.04705486, -0.21841231, -0.06237337, ...,  0.05460539,
        -0.12745559,  0.15030509],
       ...,
       [ 0.15893039, -0.21725714,  0.2248942 , ...,  0.02562923,
         0.19654563,  0.16273731],
       [ 0.05975644, -0.30435473, -0.01884911, ...,  0.17754667,
         0.27339774,  0.10985861],
       [ 0.1062359 , -0.22391617,  0.27818364, ...,  0.20405923,
        -0.11662724, -0.01496226]], dtype=float32)

In [41]:
nasa_tweets_vec.shape

(114, 96)

In [42]:
for tweet in jeff_tweets:
    print(tweet.text)
    print(vectorize_tweet(tweet.text))

Discussing climate, sustainability, and preserving the natural world with President @EmmanuelMacron today in Paris.… https://t.co/ry52OGekMH
[ 0.24272835 -0.2283334  -0.02567933  0.07039931  0.28563985 -0.10561692
 -0.20413731 -0.19428861 -0.02860477 -0.08598558  0.59878033  0.04336151
 -0.24244657  0.21892138 -0.24138747 -0.20957336 -0.04439677 -0.58222467
 -0.24877648  0.22996293 -0.10680761 -0.06657393 -0.30854216  0.22838186
 -0.07558546  0.14907461  0.0067634   0.10827582  0.03726761 -0.10144673
 -0.0895719   0.18029921 -0.19243333 -0.10673214  0.20879032 -0.04277802
 -0.09075312  0.06459248 -0.01992889  0.2143513  -0.19452918 -0.00520619
 -0.15507206  0.3682757  -0.19298345 -0.10124011  0.08351295 -0.00165736
 -0.10678323 -0.04919454  0.01009935  0.00620838  0.18240646  0.00731205
 -0.07902095  0.07742196 -0.14972031  0.16413827 -0.18740723 -0.0930818
  0.45659217  0.17622359 -0.06953519 -0.18359226 -0.17031321 -0.15189128
 -0.2642556   0.00664117 -0.0992988   0.1603092  -0.19735

In [43]:
jeff_tweets_vec = np.array([vectorize_tweet(tweet.text) for tweet in jeff_tweets])

In [44]:
jeff_tweets_vec

array([[ 0.24272835, -0.2283334 , -0.02567933, ...,  0.16770232,
        -0.03415189,  0.05669243],
       [ 0.15387794,  0.11360475,  0.16392364, ...,  0.31951156,
         0.10325204,  0.12163479],
       [ 0.09383198,  0.1428592 ,  0.02291863, ...,  0.1494844 ,
        -0.15196325,  0.09820622],
       ...,
       [ 0.27332473, -0.13436131,  0.1542285 , ...,  0.05002733,
         0.03555092,  0.10489374],
       [ 0.4294793 , -0.10777918,  0.12475884, ...,  0.22315489,
         0.13328613,  0.07689492],
       [ 0.41516918, -0.29625255, -0.02715374, ...,  0.14360304,
         0.01678687,  0.04616653]], dtype=float32)

In [45]:
jeff_tweets_vec.shape

(186, 96)

In [46]:
vects = np.vstack([nasa_tweets_vec, jeff_tweets_vec])

In [47]:
vects[0]

array([ 1.85173616e-01, -1.33187264e-01,  6.39892966e-02,  5.79700731e-02,
        2.58966327e-01, -8.83494020e-02, -1.92539275e-01,  4.42613363e-02,
       -3.41210440e-02, -1.37922928e-01,  1.69979006e-01, -1.59201786e-01,
        1.83297262e-01, -1.45774379e-01, -4.45709415e-02, -1.05901539e-01,
        8.27725306e-02, -4.48699780e-02, -4.00798544e-02,  3.22756767e-02,
       -7.64865568e-03,  9.78409350e-02, -1.34760022e-01, -1.63172781e-01,
        9.38174725e-02, -2.77234297e-02, -1.06998317e-01,  1.03367336e-01,
        1.43353119e-01,  1.17691889e-01, -2.07241163e-01,  9.14771226e-05,
       -2.24608421e-01, -7.31307501e-03,  1.98062770e-02,  9.66169536e-02,
       -7.90692419e-02, -2.05112938e-02,  3.30743045e-02,  7.91417584e-02,
       -1.16363995e-01,  1.50330141e-01, -6.85996637e-02, -1.03802033e-01,
       -2.16518473e-02, -1.30617619e-01,  2.31081918e-02, -9.95141938e-02,
       -5.26558496e-02,  4.83925976e-02,  2.88570046e-01,  8.09854642e-02,
        6.94535449e-02,  

In [48]:
vects.shape

(300, 96)

In [49]:
labels = np.concatenate([np.zeros(len(nasa_tweets)), np.ones(len(jeff_tweets))])

In [50]:
labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [51]:
log_reg = LogisticRegression().fit(vects, labels)

In [52]:
log_reg

LogisticRegression()

In [53]:
some_text = "Let's go to the moon"

In [54]:
some_text_vec = vectorize_tweet(some_text)

In [55]:
some_text_vec

array([ 0.3889306 , -0.278742  , -0.37328848,  0.1579232 ,  0.38003576,
        0.47390354,  0.03417005, -0.13161716, -0.1048806 , -0.37080958,
        0.09521268, -0.25180614, -0.3657877 , -0.3721176 , -0.21082617,
       -0.35276842,  0.37427685,  0.23143382, -0.05332935, -0.29882285,
       -0.17451762,  0.33604804, -0.14160663,  0.42909074,  0.08742448,
        0.16503577, -0.1262346 , -0.28099465, -0.12172937,  0.35508147,
        0.01165233, -0.18995565,  0.28960815, -0.3179922 ,  0.43407288,
        0.06489079,  0.06130033, -0.567842  , -0.41979358, -0.03523063,
       -0.31236044,  0.3387253 , -0.02425256, -0.0646436 , -0.07621639,
       -0.25270572, -0.04443146,  0.16871528,  0.18496798, -0.2180837 ,
        0.47259876, -0.07583344,  0.00927775,  0.7774246 , -0.25466058,
       -0.45461527,  0.3560368 ,  0.31069732,  0.35077825, -0.15059161,
        0.19384831,  0.15966238, -0.38626778, -0.0223237 ,  0.21692161,
       -0.05086028, -0.22648217, -0.6518908 , -0.14152771,  0.07

In [56]:
len(some_text_vec)

96

In [57]:
some_text_vec = some_text_vec.reshape(1, -1)

In [58]:
len(some_text_vec)

1

In [59]:
log_reg.predict(some_text_vec)

array([1.])

In [60]:
pickle.dump(log_reg, open('lr_model.sav', 'wb'))

In [61]:
loaded_model = pickle.load(open('lr_model.sav', 'rb'))

In [62]:
some_text2 = 'Black Holes and Multiverses'
some_text2_vec = vectorize_tweet(some_text2).reshape(1, -1)

In [63]:
loaded_model.predict(some_text2_vec)

array([1.])